### ISSUE TITLE
Имя автора

### ISSUE THREAD

**Issue by BlackPatrick** [terratensor/tg-svodd-bot#12]
У меня идея для развития телеграм-канал. Попробовать добавить в автоматическую трансляцию обсуждения имя автора на форуме ФКТ. В целом, при постоянном чтении уже есть понимание кто и кому отвечает, но наглядность бы не помешала. Чем на мой взгляд телеграм-канал лучше, чем чтение сообщений на форуме, так это автоматическое обновление ленты. Если читать только форум, то для просмотра новых сообщений надо все время обновлять страницу. Также на форуме браузер не запоминает где ты остановился при последнем подключении.

Есть ли техническая возможность добавить к трансляции автора сообщения?

**Comment by audetv** [comment]
Хорошо, давайте обсуждать. Но если сразу перейти к части вопроса:

> Есть ли техническая возможность добавить к трансляции автора сообщения?

то ответ да, техническая возможность есть. Но возникает вопрос, а точно это нужно, зачем? То что сейчас сделано, сделано намерено, и для текущей реализации необходимо было совершить дополнительные действия с текстом сообщения, что бы исключить имена авторов из него. Парсер их специально оттуда убирает. Сделано это было в качестве эксперимента, с целью тренировки, назовем эту тренировка так: тренировка личной меры. Тема соборная и читать и относиться к сообщениям в ней можно не только на основании имен и персоналий, а на смысле высказываний и описаний процессов. Но то, что после форума так не привычно — это факт. 

То что так сделано не означает, что это единственное правильное решение, давайте обсуждать. Но правильность решений зависит от цели. Если мы сочтем, что цели описанной мной выше не надо следовать, или эффект несущественный, то это будет обоснованием для другой технической реализации.

> Чем на мой взгляд телеграм-канал лучше, чем чтение сообщений на форуме, так это автоматическое обновление ленты. Если читать только форум, то для просмотра новых сообщений надо все время обновлять страницу.

С этим согласен, но на мой взгляд в телеграм канале есть одно большое жирное **НО!** туда нельзя написать сообщение, которое попадет на форум. Способствует телеграм канал этому? Я имею ввиду тому, чтобы у человека появилось желание писать в тему, а не только листать ленту? Я пока не знаю. Мне представляется, что в основном новые подписчики канала читают трансляцию и являются потребителями, скорее всего не все и может мои представления не верны. Несмотря на то, что подписчик может быть только читателем, я считаю, что личная мера такого читателя обсуждения прокачивается тоже, а не только у писателей в тему, иначе бы не стал делать этот канал. 

Думаю, что человек, даже только читая соборную тему, может получить много для развития. Так сказать, возьмет власть в свои руки и на своем месте будет делать то, что способствует становлению его человеком, для этого не обязательно писать в тему… А если возникнут условия, то человек сможет, захочет и начнет писать сообщения в соборную тему. Способствует телеграм канал возникновению такого условий? 

А нужны в теме сотни людей, которые будут писать свои мысли?

Способствует ли телеграм канал, как технология, развитию личной меры, дает ли возможность участвовать в соборной теме? 
Способствует ли тому, чтобы у человека открылась возможность участвовать в обсуждении, вносить вклад и свои мысли?

Вопросов много, но эти вопросы возникли отнюдь не из за вашего вопроса про имя автора, это больше концептуальные вопросы, они ранее у меня возникли, но раз мы начали обсуждение, я не могу их не задать)

Вот я сейчас это написал все это про читателей-потребителей и увидел себя)) я же в основном читатель этой темы, но писательские навыки применяю в другой сфере, и все равно пытаюсь, способствую и поддерживаю соборную тему так, как я могу, это мой произвол. Так что, видимо, телеграм канал несмотря на то, как мне кажется, что больше способствует чтению сообщений, чем писанию, все же хороший инструмент для развития.

И под конец сообщения пришла мысль в связи с соседним обсуждением в геоматрице: https://github.com/terratensor/geomatrix/issues/60#top
Телеграм канал точно способствует становлению связей, связей между людьми, событиями и различными процессами, так что не смотря на репутацию телеграмма, как источника высокочастотного кала, ему надо дать шанс, а именно использовать технологию с пользой для развития.

**Comment by iprst** [comment]
Телега целенаправленно освобождена от имён.

**Comment by BlackPatrick** [comment]
> а точно это нужно, зачем?

Я тоже об этом думал. Попробую пояснить, как я пришел к тому, что все-таки имя автора нужно. Но в качестве вводной раскрою почему я считаю ТГ удобным для чтения. Я на какое-то время от чтения форума отвалился именно по той причине, что постоянное блуждание между вопросами и обсуждениями требовало очень много времени. Для формирования своего информационного поля я тогда стал использовать телеграм, как быстрый способ получения новостей, а наиболее интересные и маркерные стал транслировать на созданный для себя канал и там же стал делать некоторые записи со своими размышлениями, но не хватало обсуждения этих размышлений с кем-то. Когда я узнал, что появилась единая соборная тема с переключением между вопросами, тогда уже стало возможным более системно читать обсуждения на форуме (к другим вопросам задаваемым на форуме теперь практически не обращаюсь), но и в этом варианте не хватало того, чтобы было все в одной ветке и тут увидел что есть тг-канал, в котором теперь все обсуждение формируется в одной ленте даже после переключения между темами. Подключившись к нему, стал читать ветку и тут как раз таки столкнулся с тем, что > в телеграм канале есть одно большое жирное **НО!** и соответственно я предложил добавить к постам в ТГ ссылку на источник. Это нужно было для того, чтобы можно было нажав на него оперативно перейти в обсуждение к конкретному сообщению и уже на форуме написать ответ. Считаю, что это **НО!** уже теперь закрыто. Писать оттуда сообщение на форум излишне. Если бы такая возможность была, то тогда бы обсуждение могло бы во много перейти в ТГ, так как там для живого общения больше технических возможностей, но оно бы при этом превратилось во флуд. Что же касается имен авторов, то тут на мой взгляд оСВОения информации, особенно для новичков, присвоение имен авторов нужно для того, чтобы из калейдоскопа сообщений он мог формировать целостную нить диалогов. Это будет помогать развивать личную меру.
 
> чтобы у человека появилось желание писать в тему, а не только листать ленту?

На мой взгляд на этом не стоит заострять внимание. Здесь из моих личных наблюдений, даже не собирая какой-то статистики, я сделал вывод, что к общению в любом сообществе и на любом ресурсе включается не более 10%. Остальные так или иначе остаются читателями. Они либо не пишут вовсе, либо пишут редко. Это вполне естественный, на мой взгляд, процесс. 

> Сделано это было в качестве эксперимента, с целью тренировки, назовем эту тренировка так: тренировка личной меры.

Тренировка хорошая и я ее на себе ощутил, но такая тренировка будет отталкивающей для новичков.

> после форума так не привычно — это факт.

К этому привыкаешь, но надо ли?

> Мне представляется, что в основном новые подписчики канала читают трансляцию и являются потребителями, скорее всего не все и может мои представления не верны.

Надо этот канал зарегистрировать на tgstat, прикрутить к нему их бота формирующего статистику по пользователям.

> Несмотря на то, что подписчик может быть только читателем, я считаю, что личная мера такого читателя обсуждения прокачивается тоже, а не только у писателей в тему, иначе бы не стал делать этот канал.

Согласен

> А если возникнут условия, то человек сможет, захочет и начнет писать сообщения в соборную тему. Способствует телеграм канал возникновению такого условий?

Однозначно способствует. И тут на мой взгляд привязка имен будет усиливать этот эффект.

> А нужны в теме сотни людей, которые будут писать свои мысли?

Нет, их и не будет, о чем я и писал выше, пишут около 10%, но этого и достаточно чтобы эффект сотой обезьяны начал работать. 

> Способствует ли телеграм канал, как технология, развитию личной меры, дает ли возможность участвовать в соборной теме?
> Способствует ли тому, чтобы у человека открылась возможность участвовать в обсуждении, вносить вклад и свои мысли?

Да, я тому пример.

> Вопросов много, но эти вопросы возникли отнюдь не из за вашего вопроса про имя автора, это больше концептуальные вопросы, они ранее у меня возникли, но раз мы начали обсуждение, я не могу их не задать)

У меня тоже эти вопросы стояли. Так что поддерживаю. что надо обсуждать

> не смотря на репутацию телеграмма, как источника высокочастотного кала, ему надо дать шанс, а именно использовать технологию с пользой для развития.

Безусловно надо. Я не программист, но готов генерить идеи по развитию и участвовать в тестировании решений и обсуждении результатов.

**Comment by BlackPatrick** [comment]
> Телега целенаправленно освобождена от имён.

Почему?

**Comment by iprst** [comment]
> > Телега целенаправленно освобождена от имён.
> 
> Почему?

Несколько причин. Тележное обезличивание имеет полезные свойства.
Тренирует личную меру пользователя телеги — он смотрит не на аватарки, а на модули. 
Поток информации освобождён от лишних стопоров, это спрямляет его доставку.
Побуждает оспорить или поддержать модуль, таким образом возникает переход на сайт. 
На сайте возникают _**грозные аватарки**_ и подключения не происходит. 
Однако нарабатывается привычка оценивать информацию по модулю.
Раньше или позже эта привычка делает пробой в системе защиты пользователя и он начинает писать. 

И таких сценариев можно много придумать. 

> Я на какое-то время от чтения форума отвалился именно по той причине, что постоянное блуждание между вопросами и обсуждениями требовало очень много времени.

Тему СВОДД сделали именно по этой причине. Теперь я вообще не блуждаю по форуму. Анальная перемодерация показала свою неэффективность, это управление не работает. Вредные модули легко детектируются и выдавливаются, а полезные развиваются и укрепляются без какой-либо модерации от слова совсем. Урок. 

> Когда я узнал, что появилась единая соборная тема с переключением между вопросами, тогда уже стало возможным более системно читать обсуждения на форуме (к другим вопросам задаваемым на форуме теперь практически не обращаюсь), но и в этом варианте не хватало того, чтобы было все в одной ветке и тут увидел что есть тг-канал, в котором теперь все обсуждение формируется в одной ленте даже после переключения между темами.

Задолго до телеги:
★ https://svodd.ru/bolshaya-svoddnaya-tema?sort=-date

> Писать оттуда сообщение на форум излишне. Если бы такая возможность была, то тогда бы обсуждение могло бы во много перейти в ТГ, так как там для живого общения больше технических возможностей, но оно бы при этом превратилось во флуд.

Технические ограничения систем это _**благо**_. Ограничениями можно и нужно пользоваться. 

> присвоение имен авторов нужно для того, чтобы из калейдоскопа сообщений он мог формировать целостную нить диалогов

Картину целостной делают не имена с аватарками, а личная мера наблюдателя. Это работа. 

> к общению в любом сообществе и на любом ресурсе включается не более 10%. Остальные так или иначе остаются читателями. Они либо не пишут вовсе, либо пишут редко. Это вполне естественный, на мой взгляд, процесс.

Наблюдение верное. Однако вывод о естественности процесса ничем не подкрепляется: в действительности неизвестно, является ли такое положение дел естественным, или сложилось в интернете вследствие работы фабрик троллей. Я знаю форумы, где 80% людей участвуют в обсуждениях. Это зависит исключительно от личных мер и нравственностей участников процесса. 

> такая тренировка будет отталкивающей для новичков

Мера растёт через нехочу.

**Comment by BlackPatrick** [comment]
> Однако вывод о естественности процесса ничем не подкрепляется:

Конечно, я так и написал, что на мой субъективный взгляд. Тут скорее дело в том, что это уровень можно изменить, но для этого количество людей, обладающих достаточными знаниями и понятийным аппаратом должно расти. Не включаются они в обсуждение скорее всего потому, что им либо не все понятно, либо они не имеют за спиной нужного багажа для того, чтобы им пользоваться. Это скорее всего проблема в образованности людей, которая последнее время снижалась по причине падения уровня образования. Второй фактор это "многабукафф". Людей приучили потреблять информацию короткими порциями или яркими образами. Писать или читать большие портянки сейчас мало кто хочет

> Я знаю форумы, где 80% людей участвуют в обсуждениях

Такие случаи знаю есть, но это скорее исключение из правил. Это происходит там, где как раз таки собираются те, кто готов на это и имеет возможность (обладает достаточными знаниями и понятийным аппаратом)

> Мера растёт через нехочу.

Как имя автора (без злобной картинки) будет мешать этому?

**Comment by BlackPatrick** [comment]
> Задолго до телеги:
> ★ https://svodd.ru/bolshaya-svoddnaya-tema?sort=-date

Да, это тоже вариант, но как я уже пояснял, на сайте не функции автообновления и возвращения к последнему непрочитанному сообщению. Поэтому ТГ-канал считаю на сегодня самым удобным для чтения.

**Comment by iprst** [comment]
> Конечно, я так и написал, что на мой субъективный взгляд.

Разумеется, но дело не в этом. Наблюдение ваше верно, и вывод _кажется_ верным, однако если мы подумаем, то не найдём реальных естественных причин того, почему ситуация сложилась именно _так_. С точки зрения управления это абсолютно управляемый процесс, который управляется авторитетами и поддерживается толпой. 

> Не включаются они в обсуждение скорее всего потому, что им либо не все понятно, либо они не имеют за спиной нужного багажа для того, чтобы им пользоваться. Это скорее всего проблема в образованности людей, которая последнее время снижалась по причине падения уровня образования. Второй фактор это "многабукафф". Людей приучили потреблять информацию короткими порциями или яркими образами. Писать или читать большие портянки сейчас мало кто хочет

То что вы описали имеет место, но это называется рационализацией. То есть вы описали факт, квитанцию, то что существует и то, каковы квазиестественные причины этому. Но это не фактические причинно-следственные связи в большой матрице процессов, вот в чём дело. До этой матрицы нам ещё копать. 

> Такие случаи знаю есть, но это скорее исключение из правил. Это происходит там, где как раз таки собираются те, кто готов на это и имеет возможность (обладает достаточными знаниями и понятийным аппаратом)

Верно, но я приводил пример не с такой целью. Могу привести другой. Любой человек, который не является глухонемым, сумеет петь. Вопрос — почему на планете не 100% населения «обладают талантом к пению», а только несколько тысяч человек? Ответ достаточно страшный — управление. 

> Как имя автора (без грязной картинки) будет мешать этому?

Имя автора является индексом из списка авторитетов. 
Нет имени — нет индекса, нет индекса — нет списка авторитетов.
Толпоэлитарность, прощай (с) 

> на сайте не функции автообновления и возвращения к последнему непрочитанному сообщению

Для запоминания позиции скролла окна можно сделать функцию, и дать для неё галочку в личном кабинете. Мне например удобно, когда окно остаётся наверху на самом новом комментарии. Но вообще это техническое ограничение также является побуждающим — соборная тема подразумевает живую воду, а не удобное чтение.

**Comment by audetv** [comment]
> > Задолго до телеги:
> > ★ https://svodd.ru/bolshaya-svoddnaya-tema?sort=-date
> 
> Да, это тоже вариант, но как я уже пояснял, на сайте не функции автообновления и возвращения к последнему непрочитанному сообщению. Поэтому ТГ-канал считаю на сегодня самым удобным для чтения.

Это технический момент, его можно решить. Например автообновление страницы можно реализовать по таймеру и вызывать простую js функцию `location.reload();`, которая перезагружает станицу.
Что то типа того: 
```
setInterval( () => location.relaod(), 60000);
```
Перезагрузка страницы 1 раз в минуту, и все. Можно более изощренным способом это сделать, для тех кто не любит простоту, но это самый простой вариант. 

Для того чтобы запоминать сообщения, нужно реализовать более сложный алгоритм, и я пока не знаю как его сделать. Т.е. не думал в деталях об этом, не имею технического решения, его надо создать. Основная особенность это то, что 100% эта функция будет работать только для зарегистрированных и залогиненных пользователей. Кажется, что запомнить позицию чтения простая вещь, но на самом деле не очень, есть технические особенности. Но это тоже можно решить. 

Мысль по отслеживанию прочитанных, сообщений появилась у меня еще на этапе создания своддной темы. Но для ее реализации не нашлось времени, и цель мы такую не ставили. Хотя в следующей версии с Reactjs у меня отмечен этот функционал отмечен для реализации, планировал. А так как по итогу нужна регистрация пользователя, то можно и нужно сделать кабинет пользователя с функционалом для работы, функционал пока еще в процессе осмысления. И пока не хватает на все ресурсов, времени, чтобы все задуманное реализовывать быстрою. 

Поэтому телеграм канал =))

**Comment by iprst** [comment]
> А так как по итогу нужна регистрация пользователя, то можно и нужно сделать кабинет пользователя с функционалом для работы, функционал пока еще в процессе осмысления.

Так точно. 

> И пока не хватает на все ресурсов, времени, чтобы все задуманное реализовывать быстрою.

Мы можем нанять сотрудников. Но надо сделать, чтобы они платили нам, а не наоборот!

**Comment by BlackPatrick** [comment]
> С точки зрения управления это абсолютно управляемый процесс, который управляется авторитетами и поддерживается толпой.

Абсолютно согласен. 

> Но это не фактические причинно-следственные связи в большой матрице процессов

Несомненно

> Ответ достаточно страшный — управление.

Я в принципе понимаю о чем вы говорите. Это управление в рамках БК. Наша глобальная задача такое управление перехватывать и учить управлять людей самим. Поэтому не транслировать имена в телегу Вы меня убедили. Толпоэлитарность прощай. 

> Для запоминания позиции скролла окна можно сделать функцию, и дать для неё галочку в личном кабинете.

Вот тут неясно о какой галочке идет речь. Я не программист, мой понятийный аппарат и знания в этой области на уровне профана. Разобраться смогу, но надо разжевать.

> Это технический момент, его можно решить. Например автообновление страницы можно реализовать по таймеру и вызывать простую js функцию `location.reload();`, которая перезагружает станицу.

Вот это для меня что-то полуизвестное. Понимаю, что это код, но не понимаю где его применить.

> Основная особенность это то, что 100% эта функция будет работать только для зарегистрированных и залогиненных пользователей.

Так это же хорошо, пусть работает только для них

**Comment by iprst** [comment]
> Вот тут неясно о какой галочке идет речь. Я не программист, мой понятийный аппарат и знания в этой области на уровне профана. Разобраться смогу, но надо разжевать.

Галочки пока не существует. Даже личного кабинета пока не существует по сути, есть только форма регистрации, авторизации и далее пока ничего, кроме одной технической функции модерации — переноса темы в новую, она есть видимо только у админов, то есть кого Алексей добавил. Но концептуально кабинет в зачаточном состоянии как-бы «есть». 

На сайт может быть добавлен функционал, о котором вы говорите, его пояснил Алексей выше. Там где функция. Её нигде не нужно применять, она приведена для примера того о чём речь. Если функционал будет реализован, он будет в личном кабинете на сайте включаться и выключаться чекбосом, то есть галочкой. Но это не сейчас. Сейчас пока телега и наибольшая удобность для тех, кто читает сайт со смартфона в приложении ТГ.

**Comment by BlackPatrick** [comment]
> Галочки пока не существует.

Все, теперь ясно.

**Comment by BlackPatrick** [comment]
@audetv Алексей, Вы, как я понимаю, на сайте форуме администратор. У меня есть технический вопрос по нему. Могу задать?

**Comment by iprst** [comment]
Задавайте, зачем тратить комментарий на разрешение.

**Comment by BlackPatrick** [comment]
У меня в личном кабинете не работает функция смены аватарки. Пытался написать обращение в техподдержку, но и оно не работает))) можете как-то проверить что не так?

**Comment by iprst** [comment]
Функция смены аватарки на ФКТ отсутствует. В личном кабинете есть заглушка-пустышка, но она не работает. Для смены аватарки нужно взять ту почту, на которую зарегистрирован аккаунт на ФКТ, перейти на [gravatar.com](https://en.gravatar.com/), пройти регистрацию, загрузить нужное изображение, сохранить как основную аватару и дождаться несколько минут (редко — часов) пока сервисы не обновят базы аватар и не начнут отображать новые. Если на эту почту есть регистрации на других сайтах, которые поддерживают граватар, и где вы не загружали собственную аватарку, везде подтянется эта, общая.

**Comment by BlackPatrick** [comment]
О, как все устроено оказывается. Но форма обратной связи для техподдержки все равно не работает

**Comment by iprst** [comment]
> форма обратной связи для техподдержки все равно не работает

Вряд ли Алексей её починит, ведь если бы у него был доступ к администрированию сайта ФКТ, зачем бы ему потребовалось городить целый парсер для комментариев, если их можно было просто забирать непосредственно из базы данных… 💯

**Comment by audetv** [comment]
> @audetv Алексей, Вы, как я понимаю, на сайте форуме администратор? У меня есть технический вопрос по нему. Могу задать?

Выше все верно написано, я не являюсь администратора сайта ФКТ. 

Поводу неработающей формы обратной связи, вспомнился пример, которым в том числе обосновывают необходимость иметь автоматические тесты для написанного кода. Если форма сломалась или не работает, то без теста программист об этом даже не узнает, так как у пользователей нет возможности ему об этом сообщить, круг замкнулся. Пишите письма, если есть email, но там их не читают). 

Но здесь я думаю проблема глубже, на форуме можно написать или задать вопрос и передать сигнал, так что скорее всего нехватка ресурсов в сумме с нежеланием что-то менять.

**Comment by BlackPatrick** [comment]
> Но здесь я думаю проблема глубже, на форуме можно написать или задать вопрос и передать сигнал, так что скорее всего нехватка ресурсов в сумме с нежеланием что-то менять.

Я тоже так думаю и поэтому не особо заморачивался. Это уже здесь решил спросить, раз появилась такая возможность. Написать в поддержку хотел как раз таки по поводу аватарки, но раз мне Сергей тут пояснил, то уже и не буду их беспокоить. Спасибо
