### ISSUE TITLE
Разработать модуль, который бы обрезал ссылки на телегу в комментариях

### ISSUE THREAD

**Issue by audetv** [terratensor/tg-svodd-bot#16]
Есть такая идея к обсуждению. Предлагаю рассмотреть модуль для парсера сайта и телеграм канала, который бы обрезал ссылки на телегу, не затрагивая все остальные ссылки. То есть из ссылок вида 
```
https://t.me/aaaaabbbbb111111
```
Делал текст вида
```
t.me/aaaaabbbbb111111
```
Без создания прямой ссылки. Таким образом мусор не будет ретранслироваться в качестве прямых ссылок, что не позволит делать из ресурса ретрансляционную помойку.

_Originally posted by @iprst in https://github.com/terratensor/tg-svodd-bot/issues/15#issuecomment-1751701445_

**Comment by iprst** [comment]
А старые ссылки можно будет обрабатать ретроспективно?

**Comment by audetv** [comment]
В телеграмме нет, точнее можно, но довольно сложно, надо как-то получить id каждого отправленного сообщения, я их не сохранял и потом отредактировать все эти сообщения. Но надо ли это делать? 

А вот в поиске и в комментариях на svodd.ru да, там просто режим включу для отображения всех ссылок из ТГ. 
Можно даже в будущем в кабинете сделать настройку, чтобы включать ТГ ссылки, но только для себя, если пользователь это хочет… и за большие деньги, для отчетов сойдет)

**Comment by iprst** [comment]
> В телеграмме нет, точнее можно, но довольно сложно, надо как-то получить id каждого отправленного сообщения, я их не сохранял и потом отредактировать все эти сообщения. Но надо ли это делать?

Если нет, то и не будем огород городить. Эксперимент же. 

> Можно даже в будущем в кабинете сделать настройку, чтобы включать ТГ ссылки, но только для себя, если пользователь это хочет… и за большие деньги, для отчетов сойдет)

)))

**Comment by audetv** [comment]
Ахаха, предполагал:
<details><summary>Details</summary>
<p>

![2023-10-07_17-54-13](https://github.com/terratensor/tg-svodd-bot/assets/10896447/65e836d0-c77a-488b-b61a-76514321a475)

</p>
</details> 

Т.е. телеграмм даже с вырезанной схемой в урл благополучно сам делает рабочую ссылку на канал.

**Comment by iprst** [comment]
Что будет, если перед ним поставить любой другой символ типа тире — скопировать и открыть адрес можно, а ссылка не должна создаваться?

**Comment by audetv** [comment]
> Что будет, если перед ним поставить любой другой символ типа тире — скопировать и открыть адрес можно, а ссылка не должна создаваться?


Да да, уже, тогда так:
<details><summary>Details</summary>
<p>

![2023-10-07_17-59-21](https://github.com/terratensor/tg-svodd-bot/assets/10896447/e15e642b-42bd-478f-82d0-105e119e06ab)


</p>
</details>

**Comment by iprst** [comment]
СЛАВНО

**Comment by audetv** [comment]
И сразу попадание: https://t.me/svoddru/6334

Следующий этап — добавить на svoddd.ru

**Comment by iprst** [comment]
Прямо органика пошла.

**Comment by audetv** [comment]
> Почему-то при транслировании поста в телеграм ссылка обрезалась.
> 
> Она обрезалась не почему-то, а согласно одному issue, закрытому пару дней назад. В качестве эксперимента, временно. Текст ссылки на телегу остаётся, её можно открыть скопировав, но сама физическая ссылка в ленте не формируется. С остальными ссылками, которые не касаются телеги, всё по прежнему, они работают в обычном режиме.

> Текст ссылки на телегу остаётся, её можно открыть скопировав, но сама физическая ссылка в ленте не формируется.
> 
> А какая цель?

@BlackPatrick упоминаемый issue

**Comment by iprst** [comment]
Ага, ответил в теме.

**Comment by BlackPatrick** [comment]
> Ага, ответил в теме.

Увидел, цель понятна.
