### ISSUE TITLE
Обработка больших сообщений, обрубает на полуслове

### ISSUE THREAD

**Issue by audetv** [terratensor/tg-svodd-bot#5]
Можно телеговский issue открыть, но пока тут напишу — думаю переносы по количеству символов в будущем стоит придвинуть к переносам по словам, если вообще не по предложениям. Сейчас на полуслове может обрубить.

_Originally posted by @iprst in https://github.com/terratensor/tg-svodd-bot/issues/4#issuecomment-1675954654_

**Comment by audetv** [comment]
Причем необходимо отслеживать, чтобы сообщение при разбивке имело и открывающие и закрывающие тэги, а инцидентах ниже, большая цитата была разбита на чанки по 496 символов, но в первой части был открывающий <i>, во второй закрывающий </i>, итого телеграм отклонил эти сообщения и они не попали в ленту.
[TG-SVODD-BOT-3](https://svodd.sentry.io/share/issue/ded0d715f0014db7aab7b9fe64f31abe/)

[TG-SVODD-BOT-4](https://svodd.sentry.io/share/issue/0a2e970ae2a34beb9afd1b4d1d6f1231/)

Надо применить практику разбивки больших параграфов из библиотеки, с поправкой на теги.

**Comment by iprst** [comment]
> Надо применить практику разбивки больших параграфов из библиотеки, с поправкой на теги.

Видимо это наиболее адекватный сегодня вариант, ага.

**Comment by audetv** [comment]
Сейчас еще понял, что 99% будет проблема с доставкой старых сообщений при переходе на новую тему. 

Т.е. сейчас нет механизма, который отправит уже созданные сообщения из новой темы, созданные до того, как сайт был переключен на новую тему. 

Т.е. как минимум первое сообщения новой темы со ссылками и возможно несколько следующих сообщений, которые пользователи оставят в новой теме не будут отправлены. И когда будет произведено переключение темы на сервере в консоли, эти сообщения так и останутся неотправленными. В целом вопрос решаемый, надо просто доработать алгоритм, чтобы после переключения было произведено прочтение всех комментариев в новой теме и отправка их, но пока могут быть потери.

@iprst Итого, к чему я это все подумал и понял, я сегодня днем буду без компьютера, с этого момента чуть позже. И не смогу переключить тему, если вы решите обновить и сделать 38 тему. 
Просьба, если вы планировали переключение в ближайшее время, сегодня днем, отложить до вечера, когда я буду у компьютера и смогу оперативно переключить тему.

**Comment by iprst** [comment]
> Итого, к чему я это все подумал и понял, я сегодня днем буду без компьютера, с этого момента чуть позже. И не смогу переключить тему, если вы решите обновить и сделать 38 тему.
> Просьба, если вы планировали переключение в ближайшее время, сегодня днем, отложить до вечера, когда я буду у компьютера и смогу оперативно переключить тему.

Принято, вовремя вам об этом пришла в голову мысль, хорошо. Поскольку как раз думал как будет время сегодня подыскать подходящий новый вопрос. Отложу в таком случае открытие до завтра-послезавтра.

**Comment by audetv** [comment]
Сделал обновление https://github.com/terratensor/svodd/pull/224
Теоретически 90%, что все будет работать, во всяком случае на локальном протестировал, работало. 
Пользователь с правами администратора теперь может менять тему прямо на сайте, даже с телефона, надо только вспомнить как в режим разработчика на телефоне в браузере входить, чтобы ИД открывающего комментария посмотреть и добавить в форму. И добавил вам права администратора, на всякий случай, пусть будут.

**Comment by iprst** [comment]
> надо только вспомнить как в режим разработчика на телефоне в браузере входить, чтобы ИД открывающего комментария посмотреть и добавить в форму.

Можно процитировать — в цитате будет указан id. 

> Пользователь с правами администратора теперь может менять тему прямо на сайте

А куда жать надо?

**Comment by audetv** [comment]
> > надо только вспомнить как в режим разработчика на телефоне в браузере входить, чтобы ИД открывающего комментария посмотреть и добавить в форму.
> 
> Можно процитировать — в цитате будет указан id.

Да, точно.

> А куда жать надо?

https://svodd.ru/cabinet

**Comment by iprst** [comment]
> https://svodd.ru/cabinet

Супер. Завтра протестируем значит эту схему, подготовлю всё и просигналю, сообразим.

**Comment by iprst** [comment]
Для подумать: может быть цитату следует приклеивать к ответу на неё, чтобы сообщения не заканчивались на курсивный блок, а ответ на цитату не оказывался оторван от неё и перенесён в следующий пост? Будет более логично, но не знаю насколько сложно осуществить условие такой проверки для парсера.

**Comment by audetv** [comment]
Да, я об этом тоже думал, тоже кажется, что так будет логичнее, и когда я эту версию писал, я уже хотел это реализовать, но не смог и пока отложил до следующей версии, т.к. на тот момент мне было не понятно, правильно ли я разбил сообщение, будет ли это хорошо работать и прочее, ещё понаблюдаю. Но в итоге после последнего обновления не было не одного exception, и все сообщения проходят сами, ничего не терялось, так что теперь можно усовершенствовать метод и приклеивать цитату. Согласен с вашим предложением.

**Comment by iprst** [comment]
> после последнего обновления не было не одного exception, и все сообщения проходят сами, ничего не терялось

Отлично. Визуально тоже всё нормально выглядит, даже сторонние картинки в виде ссылки парсятся как изображения. Рабочий метод. Можно дальше прикручивать свистелки и хотелки.
